---
# tasks file for wordpress
- name: Baixa o WordPress
  get_url:
   url=https://wordpress.org/latest.tar.gz
   dest=/tmp/wordpress.tar.gz
   validate_certs=no
 
- name: Descompacta o WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Atualiza o site Apache padrao
  lineinfile:
   dest=/etc/apache2/sites-enabled/000-default.conf
   regexp="(.)+DocumentRoot /var/www/html"
   line="DocumentRoot /var/www/wordpress"
  notify:
  - reinicia apache

- name: Renomeia o arquivo de configuracao de exemplo
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

- name: Atualiza a configuracao WordPress
  lineinfile:
   dest=/var/www/wordpress/wp-config.php
   regexp={{ item.regexp }}
   line={{ item.line }}
  with_items:
   - {regexp: 'db', line: "define('DB_NAME', '{{test_db}}');"}
   - {regexp: 'user', line: "define('DB_USER', '{{test_user}}');"}
   - {regexp: 'pass', line: "define('DB_PASSWORD', '{{test_password}}');"}
